version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    depends_on:
      - chromadb
    command: uvicorn meribot.api.app:app --host 0.0.0.0 --port 8000 --reload

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    volumes:
      - ./web/static:/usr/share/nginx/html/static
    depends_on:
      - api

volumes:
  chroma_data:
